### ISSUE TITLE
<dl> elements should be styled accordingly

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gbdoc-style#12] opened 2018-04-06 18:17 UTC
A `<dl>` is a definition list, and should be styled like a table such as in the "symbols and abbreviations" section.

<img width="367" alt="screen shot 2018-04-07 at 2 16 35 am" src="https://user-images.githubusercontent.com/11865/38437376-d6f8b12e-3a09-11e8-8d0c-f051d2735276.png">

**Comment by opoudjis** [comment] 2018-04-07 00:58
`<dl>` is rendered as a table in the word output, but is currently left as a `<dl>` in the HTML output, since I figured you wanted to keep logical mark up there, and deal with the rendering through pure CSS. I assume that remains the case?

**Comment by ronaldtse** [comment] 2018-04-07 01:01
Yes indeed, it’s a CSS task.

**Comment by ronaldtse** [comment] 2018-07-08 02:41
@pierrefortier could you help fix this issue? Thanks!

**Comment by opoudjis** [comment] 2018-07-08 05:07
This is an old ticket, and I want to make sure we're all in agreement about it, because I'm confused.

In HTML output, `<dl>` are consistently being rendered up now as tables in the gems --- with the exception of GB, because we have not had this discussion for GB:

````
dl {
  display: grid;
  grid-template-columns: max-content auto;
}

dt {
  grid-column-start: 1;
}

dd {
  grid-column-start: 2;
}

dd p, dt p {
  margin-top: 0px;
}
````

@ronaldtse I'm confused as to whether the snippet you've posted above is to-be or as-is. If you want the GB definition lists to render like they already do in ISO, as tables, then I just copy the CSS over from ISO, and it's done.

**Comment by opoudjis** [comment] 2018-07-08 05:19
Confirmed with Ronald. @pierrefortier, nothing for you to do here: I will bring the GB HTML stylesheet in line with the others.

**Comment by opoudjis** [comment] 2018-07-08 05:26
Done quick patch, want to confirm with @ronaldtse whether he wants sidebars and the full behaviour of the other gems' stylesheets.

[rice.html.zip](https://github.com/riboseinc/gbdoc-style/files/2173363/rice.html.zip)

**Comment by opoudjis** [comment] 2018-07-08 06:36
He does.

**Comment by opoudjis** [comment] 2018-07-08 09:19
OK, @pierrefortier please work on this. There's some issues remaining, but I'll wait for you.

[rice.html.zip](https://github.com/riboseinc/gbdoc-style/files/2173550/rice.html.zip)

**Comment by opoudjis** [comment] 2018-07-08 09:21
Closing this issue, it turns into https://github.com/riboseinc/gbdoc-style/issues/9

**Closed as completed by opoudjis** 2018-07-08 09:21 UTC
Labels: bug
